apiVersion: 1

datasources:
  - name: TradingData
    type: postgres
    uid: trading-data-source
    url: postgres_metadata:5432
    user: admin
    database: quant_platform
    secureJsonData:
      password: password123
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
    isDefault: true
    editable: true

  - name: MarketData (QuestDB)
    type: postgres
    uid: market-data-source
    url: questdb_tsdb:8812
    user: admin
    database: qdb
    secureJsonData:
      password: quest
    jsonData:
      sslmode: 'disable'
      postgresVersion: 13
      timescaledb: false
